name: Deploy CV

# GitHub events that triggers the workflow:
on:
  push:
    branches: ["main"]

jobs:
  # Build job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run RenderCV
        run: |
          rendercv render ../Bruno_Garrofe_CV.yaml
      - name: Upload CV
        uses: actions/upload-artifact@v4
        with:
          path: rendercv_output/Bruno_Garrofe_CV.pdf
